# Generated by Django 4.2 on 2023-04-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('messages', models.JSONField(default={'state': 0})),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, null=True)),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
