# Generated by Django 4.2 on 2023-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_user_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='A2_8',
            field=models.IntegerField(default=0),
        ),
    ]
