# Generated by Django 4.2 on 2023-04-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_user_a2_8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='B1_7',
        ),
    ]
